mqtt_client:
  ros__parameters:
    broker:
      host: "localhost"
      port: 1883
    bridge:
      ros2mqtt:
        ros_topics:
          - /hi
          - /testBool
        /hi:
          mqtt_topic: "hiMqtt"
          ros_type: "rov_msgs/msg/VehicleState"
        /testBool:
          mqtt_topic: "testBoolMqtt"
          primitive: true
      mqtt2ros:
        mqtt_topics:
          - helloMqtt
        helloMqtt:
          ros_topic: "/hello"
          primitive: true
